spring.application.name=Carsharing
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/carsharing
spring.datasource.username=postgres
spring.datasource.password=12345

jwt.secret=8x4vFqK2mP3nR5sT7uV9wY0zA1bC2dE3fG4hI5jK6lM7nO8pQ9rS0tU1vW2xY3z
jwt.expiration=86400000
jwt.refresh-token-expire-mill=604800000

app.oauth2.redirect-uri=http://localhost:5173/login
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.security.oauth2.client.registration.github.client-id=Ov23lif47FgX8aMOhjuQ
spring.security.oauth2.client.registration.github.client-secret=dad07c439ccaf4dc0f4d836fa7b41195b9aebffb
spring.security.oauth2.client.registration.github.scope=user:email,read:user

server.port=8080


logging.level.org.sharing.carsharing=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=logs/carsharing.log
logging.level.root=WARN


# Hibernate SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Hibernate schema update settings
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true


# Server port
server.port=8080